### ISSUE TITLE
client crash with colossal chests

### ISSUE THREAD

**Issue by jmoiron** [Fureniku/crafting-station#10]
tracebacks in this issue: https://github.com/jmoiron/quantum-skies/issues/14

If you place the crafting station next to a collosal chest core, things work normally.  However, if you open up a recipe view in JEI, and then attempt to `ESC` out, the client crashes with a null ptr exception and the tracebacks in the issue linked above.

I think the root cause could be related to #8.  FWIW, when next to the chest in this way, the extended crafting station UI (the X) does not display.  The previous version of the mod (1.2.1) doesn't crash and does display the extended UI in the same situation.

**Comment by Fureniku** [comment]
Merged the fix for #8 which as you said, should cover this too. Let me know if you're still having trouble!

**Comment by jmoiron** [comment]
Indeed it's fixed w/ the latest CF build, thanks!
