### ISSUE TITLE
Connected Resources button from your mod?

### ISSUE THREAD

**Issue by Neb2566** [Fureniku/crafting-station#2]
Is the Connected Resources button from your mod? If so could you add a config option to disable it or atleast to set it to auto false when opening the grid, I dont know how many times now I have shift clicked to craft something and it max crafts from available resources in chest so I end up with way more of those items then I want or even need because I forget to click it to false :P

**Comment by xanat0s** [comment]
Same here, it's getting annoying. Briefly looked thru the source to find out where the state of this toggle is being tracked but didn't see anything at first glance.

**Comment by bigfoot547** [comment]
agreed. just crafted an inventory of stone hammers. still looking for which mod this is a part of.

**Comment by Fureniku** [comment]
Fixed in most recent patch. Apologies for the delay, I didn't seem to get any notifications about this issue, think I need to check a project setting somewhere...
