### ISSUE TITLE
No JEI Integration with JEI-1.20.1  versions 15.8.x or 15.4.x

### ISSUE THREAD

**Issue by BrewingCoder** [Fureniku/crafting-station#3]
JEI "+" button missing on any newer version of JEI 15.8.x or 15.4.x  

have to downgrade to 15.3.0.1 to see the "+" re-appear.

**Comment by CrimsonCube** [comment]
It's actually enough to downgrade to 15.8.0.10, it seems like the breaking change was introduced in [this commit.](https://github.com/mezz/JustEnoughItems/commit/a2e8fe65818c1202dd7ec8be8bc4aacfe710b231)

**Comment by Fureniku** [comment]
Mostly fixed in latest release, with a minor caveat that it can't pull directly from output slots (new JEI change, beyond my control)
