### ISSUE TITLE
Missing "Move Items" button when connected to inventory

### ISSUE THREAD

**Issue by GrigorescuStefan** [Fureniku/crafting-station#5]
Minecraft version: 1.20.1
Forge version: 47.3.0 (recommended on the official website)
Mod version: latest available (1.20.1-1.2.1)
JEI version: latest available (jei-1.20.1-forge-15.11.0.43)

The "Move Items" button disappears when the Crafting Station is connected to any sort of inventory. 
I have tried to connect it to most if not all available items that have an inventory.
All have the same behavior regardless of the number connected to the Crafting Station or whether it is the slab variant or the full block variant. 
It isn't an issue of conflicting mods considering i have tested it on a fresh install of Minecraft with only the mods presented in the list at the top.
Updating to Forge 47.3.5 (latest version available for this specific Minecraft version) didn't fix it.

Connected to inventories.
![image](https://github.com/user-attachments/assets/7440d17b-44d8-483d-a7dd-c8fb0564dadd)
![image](https://github.com/user-attachments/assets/fa59820f-e4aa-44d1-80b1-c381336e7ec4)

Disconnected from any inventory.
![image](https://github.com/user-attachments/assets/6efe71ea-cdad-4c8b-8134-a934448763ff)
![image](https://github.com/user-attachments/assets/db8c4f39-d148-497f-b7de-56cbe8e8d9a1)

**Comment by Fureniku** [comment]
Mostly fixed in latest release, with a minor caveat that it can't pull directly from output slots (new JEI change, beyond my control)
