### ISSUE TITLE
Locked slots change causes moving crafting ingredients from Sophisticated Storage containers to crash

### ISSUE THREAD

**Issue by RGamberini** [Fureniku/crafting-station#8]
## Current Behavior
Pressing the "Move items" button from JEI on a crafting station with a Sophisticated Storage chest / barrel attached causes the game to crash with a null pointer exception.
[Crash Report](https://gist.github.com/RGamberini/dd0a53fade14da7d2c07588c7fb3639a)
## Cause
This is caused by the change to support "locked slots" introduced in 1681c41. Notably [these lines here](https://github.com/RGamberini/crafting-station/blob/fork/1.20.1/src/main/java/tfar/craftingstation/client/CraftingStationScreen.java#L53-L65).
The `getContainerFromId` function attempts to cast a `BlockEntity` to a `Container` and if it can't than it returns null, since [SophisticatedStorage containers do not extend Container](https://github.com/P3pp3rF1y/SophisticatedStorage/blob/1.18.x/src/main/java/net/p3pp3rf1y/sophisticatedstorage/block/BarrelBlockEntity.java) this returns an unchecked null that crashes the game.

## Possible Solution
Assuming that non-container extending tile entities cannot have locked slots, it seems reasonable to skip the locked slots check when the `getContainerFromId` method returns null.
I've submitted a [pull request](https://github.com/Fureniku/crafting-station/pull/9) that does this.

This has resolved the bug in my testing environment.

**Comment by Fureniku** [comment]
Thanks for the PR! Merged into 1.2.3 + credited you in patch notes
